version: 2

models:
  - name: silver_clicks
    description: "Avazuクリックログのクレンジング済みデータ"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: click
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: hour_ts
        tests:
          - not_null
      - name: banner_pos
        tests:
          - not_null
      - name: device_type
        tests: 
          - not_null
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5]

