name: dbt CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'dbt/**'
      
jobs:
  dbt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dbt/
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dbt
        run: pip install dbt-databricks

      - name: Setup profiles.yml
        run: | 
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          ctr_lakehouse:
            target: dev
            outputs:
              dev:
                type: databricks
                host: ${{ secrets.DATABRICKS_HOST }}
                http_path: ${{ secrets.DATABRICKS_HTTP_PATH }}
                token: ${{ secrets.DATABRICKS_TOKEN }}
                catalog: ctr_lakehouse
                schema: default
                threads: 1
          EOF
      
      - name: dbt debug
        run: dbt debug

      - name: dbt test
        run: dbt test

      - name: dbt run
        run: dbt run

        